apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: doorSensor.yaml
  name: iot-kafka-door-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-kafka-door-sensor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-kafka-door-sensor
    spec:
      containers:
        - image: intel-server-03:5000/iotkafkadoorsensors
          name: iot-kafka-door-sensor
          imagePullPolicy: Always
          env:
            - name: KAFKA_TOPIC
              value: doors
            - name: INFLUX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influx-secrets
                  key: username
            - name: INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influx-secrets
                  key: password
          envFrom:
            - configMapRef:
                name: kafka-config
            - configMapRef:
                name: influx-config
